### ISSUE TITLE
 '@sgftech/payment-razorpay@*' is not in this registry.

### ISSUE THREAD

**Issue by omesh845** [SGFTech/payment-razorpay#1]
Hello,

I recently tried using your plugin on a new project and encountered an issue: it seems that the package `@sgftech/payment-razorpay@*` isn't available in the registry. Could you let me know if this package is currently available? If it is, could you provide guidance on how to install and test it effectively?

Thank you in advance.

@SGFGOV

**Comment by SGFGOV** [comment]
@sgftech/payment-razorpay

**Comment by omesh845** [comment]
Yes, i tried it and it gave me not found error! So I downloaded the code and installed with locally, then i got the error of "main" entry error!

**Comment by omesh845** [comment]
to be exact: 
```
npm install @sgftech/payment-razorpay

npm warn ERESOLVE overriding peer dependency
npm warn While resolving: jest-config@29.7.0
npm warn Found: @types/node@22.9.0
npm warn node_modules/jest-config/node_modules/@types/node
npm warn
npm warn Could not resolve dependency:
npm warn peerOptional @types/node@"*" from jest-config@29.7.0
npm warn node_modules/jest-config
npm warn   jest-config@"^29.7.0" from @jest/core@29.7.0
npm warn   node_modules/@jest/core
npm warn   2 more (create-jest, jest-cli)
npm error code E404
npm error 404 Not Found - GET https://registry.npmjs.org/@sgftech%2fpayment-razorpay - Not found
npm error 404
npm error 404  '@sgftech/payment-razorpay@*' is not in this registry.
npm error 404
npm error 404 Note that you can also install from a
npm error 404 tarball, folder, http url, or git url.

```

**Comment by SGFGOV** [comment]
hi..

please try now. It was private package

**Comment by SGFGOV** [comment]
we can connect over discord

**Comment by omesh845** [comment]
Certainly! Could you share your Discord username?

My user ID is: `437080067936485376`.

The package has successfully installed now, but I'm encountering some errors. Specifically, the following imports:

```
import {
    cancelOrder,
    placeOrder,
    waitForPaymentCompletion,
} from "@lib/data/cart";
```

I couldn't find references to `cancelOrder` and `waitForPaymentCompletion` in the `README.md`, as well as a few other related functions when trying to place an order. 

Please connect with me on Discord so we can go over these details. Thanks!

**Comment by omesh845** [comment]
Error setting up the request: An error occurred in InitiatePayment during the creation of the razorpay payment intent: {"statusCode":400,"error":{"code":"BAD_REQUEST_ERROR","description":"The amount must be an integer.","metadata":{},"reason":"input_validation_failed","source":"business","step":"payment_initiation"}}

![image](https://github.com/user-attachments/assets/475a4d2d-db85-4e39-afda-65958b65029d)

the first payment test was sucess but from second i am getting this error!

**Comment by SGFGOV** [comment]
can you share a video of what you do, please share the browser logs if any

**Comment by omesh845** [comment]
hi, could you share or give request in discord?
well discuss over there?

My user ID is: 437080067936485376.

**Comment by SGFGOV** [comment]
you can connect govdiw#006

**Comment by OmkarHalpatrao** [comment]
![Image](https://github.com/user-attachments/assets/01953542-9b2b-49d0-9e4f-cab597be81cb)
i am getting this error
 when i comment context from this code 
try {
      const shouldInputCard =
        isStripeFunc(selectedPaymentMethod) && !activeSession

      if (!activeSession) {
        await initiatePaymentSession(cart, {
          provider_id: selectedPaymentMethod,
          context:{
            extra:cart
          }
        })
      }
 }
 .. and if i send context also then it give this error

![Image](https://github.com/user-attachments/assets/b248f196-eac8-4dc3-9801-cd5405e901fc)

**Comment by SGFGOV** [comment]
You have to pass the cart context.. Don't comment it

**Comment by SGFGOV** [comment]
@OmkarHalpatrao please create separate issue

**Comment by OmkarHalpatrao** [comment]
> [@OmkarHalpatrao](https://github.com/OmkarHalpatrao) please create separate issue

Yeah , I have already created it
